name: esm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - ld_impl_linux-64=2.43
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.11.13
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
      - biopython==1.85
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - filelock==3.18.0
      - fsspec==2025.5.1
      - hf-xet==1.1.5
      - huggingface-hub==0.33.1
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - sympy==1.14.0
      - tokenizers==0.15.2
      - torch==2.1.2
      - tqdm==4.67.1
      - transformers==4.39.3
      - triton==2.1.0
      - typing-extensions==4.14.0
      - urllib3==2.5.0
      - accelerate
      - sentencepiece
      - protobuf==3.20.*
prefix: /mnt/mini3/work/cas/miniconda3/envs/esm
